#!/usr/bin/env groovy

//ENV Vars
def TOOLS_NAMESPACE = "s4g19x-poornima-sivanand-openshift201-may2019-tools"
def DEV_NAMESPACE = "s4g19x-poornima-sivanand-openshift201-may2019-dev"
def PROD_NAMESPACE = "s4g19x-poornima-sivanand-openshift201-may2019-prod"


//Pipeline
node {
            stage ('Build Stage'){
                dir ('simple_pipeline') {
                    checkout scm
                    sh "echo HELLO WORLD! "
                    sh "ls -lha openshift-201/templates"
                }
            }
    }