---
# Source: loki/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: poornima-sivanand-loki
  labels:
    app: loki
    chart: loki-0.8.4
    release: poornima-sivanand-loki
    heritage: Tiller
data:
  loki.yaml: YXV0aF9lbmFibGVkOiBmYWxzZQpjaHVua19zdG9yZV9jb25maWc6CiAgbWF4X2xvb2tfYmFja19wZXJpb2Q6IDAKaW5nZXN0ZXI6CiAgY2h1bmtfYmxvY2tfc2l6ZTogMjYyMTQ0CiAgY2h1bmtfaWRsZV9wZXJpb2Q6IDE1bQogIGxpZmVjeWNsZXI6CiAgICByaW5nOgogICAgICBrdnN0b3JlOgogICAgICAgIHN0b3JlOiBpbm1lbW9yeQogICAgICByZXBsaWNhdGlvbl9mYWN0b3I6IDEKbGltaXRzX2NvbmZpZzoKICBlbmZvcmNlX21ldHJpY19uYW1lOiBmYWxzZQpzY2hlbWFfY29uZmlnOgogIGNvbmZpZ3M6CiAgLSBmcm9tOiAyMDE4LTA0LTE1CiAgICBpbmRleDoKICAgICAgcGVyaW9kOiAxNjhoCiAgICAgIHByZWZpeDogaW5kZXhfCiAgICBvYmplY3Rfc3RvcmU6IGZpbGVzeXN0ZW0KICAgIHNjaGVtYTogdjkKICAgIHN0b3JlOiBib2x0ZGIKc2VydmVyOgogIGh0dHBfbGlzdGVuX3BvcnQ6IDMxMDAKc3RvcmFnZV9jb25maWc6CiAgYm9sdGRiOgogICAgZGlyZWN0b3J5OiAvZGF0YS9sb2tpL2luZGV4CiAgZmlsZXN5c3RlbToKICAgIGRpcmVjdG9yeTogL2RhdGEvbG9raS9jaHVua3MKdGFibGVfbWFuYWdlcjoKICByZXRlbnRpb25fZGVsZXRlc19lbmFibGVkOiBmYWxzZQogIHJldGVudGlvbl9wZXJpb2Q6IDAK

---
# Source: loki/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: poornima-sivanand-loki
  labels:
    app: loki
    chart: loki-0.8.4
    release: poornima-sivanand-loki
    heritage: Tiller
  annotations:
    {}
    
spec:
  type: ClusterIP
  ports:
    - port: 3100
      protocol: TCP
      name: http-metrics
      targetPort: http-metrics
  selector:
    app: loki
    release: poornima-sivanand-loki

---
# Source: loki/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: poornima-sivanand-loki
  labels:
    app: loki
    chart: loki-0.8.4
    release: poornima-sivanand-loki
    heritage: Tiller
  annotations:
    {}
    
spec:
  replicas: 1
  minReadySeconds: 0
  selector:
    matchLabels:
      app: loki
      release: poornima-sivanand-loki
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: loki
        name: loki
        release: poornima-sivanand-loki  
      annotations:
        checksum/config: 5102c215461ac13d341f03fe231621a879c933d0bb3576468ea33f5e4e973fe6
        prometheus.io/port: http-metrics
        prometheus.io/scrape: "true"
        
    spec:
      serviceAccountName: default   
      containers:
        - name: loki
          image: "grafana/loki:latest"
          imagePullPolicy: Always
          args:
            - "-config.file=/etc/loki/loki.yaml"            
          volumeMounts:
            - name: config
              mountPath: /etc/loki
            - name: storage
              mountPath: "/data"
              subPath: 
          ports:
            - name: http-metrics
              containerPort: 3100
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ready
              port: http-metrics
            initialDelaySeconds: 45
            
          readinessProbe:
            httpGet:
              path: /ready
              port: http-metrics
            initialDelaySeconds: 45
            
          resources:
            {}
            
          securityContext:
            readOnlyRootFilesystem: true
          env:
            - name: JAEGER_AGENT_HOST
              value: ""
      nodeSelector:
        {}
        
      affinity:
        {}
        
      tolerations:
        []
        
      terminationGracePeriodSeconds: 30
      volumes:
        - name: config
          secret:
            secretName: poornima-sivanand-loki
        - name: storage
          emptyDir: {}


---
# Source: loki/templates/networkpolicy.yaml

---
# Source: loki/templates/pdb.yaml

---
# Source: loki/templates/podsecuritypolicy.yaml



---
# Source: loki/templates/pvc.yaml


---
# Source: loki/templates/role.yaml



---
# Source: loki/templates/rolebinding.yaml



---
# Source: loki/templates/serviceaccount.yaml



