apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: loki-template
message: |-
  The following service(s) have been created in your project: ${LOKI_SERVICE_NAME}.
  For more information about using this template, including OpenShift considerations, contact the rocketchat community.
metadata:
  annotations:
    description: |-
      Grafana Template for use in OpenShift 201 lab without persistent storage. 

      WARNING: Any configuration stored will be lost upon pod destruction. ConfigMaps should be used for codified configuration. 
    iconClass: icon-other-unknown
    openshift.io/display-name: loki-openshift201
    openshift.io/documentation-url: https://github.com/bcdevops/devops-platform-workshops
    openshift.io/long-description: This template provides a sample Grafana configuration for lab purposes.
    openshift.io/provider-display-name: BCDevOps
    openshift.io/support-url: https://github.com/bcdevops/
    tags: monitoring,loki
  name: loki-template
objects: 
- apiVersion: v1
  kind: Secret
  metadata:
    name: ${LOKI_SERVICE_NAME}
    labels:
      app: ${LOKI_SERVICE_NAME}
      chart: loki-0.8.4
      release: ${LOKI_SERVICE_NAME}
      heritage: Tiller
  data:
    loki.yaml: YXV0aF9lbmFibGVkOiBmYWxzZQpjaHVua19zdG9yZV9jb25maWc6CiAgbWF4X2xvb2tfYmFja19wZXJpb2Q6IDAKaW5nZXN0ZXI6CiAgY2h1bmtfYmxvY2tfc2l6ZTogMjYyMTQ0CiAgY2h1bmtfaWRsZV9wZXJpb2Q6IDE1bQogIGxpZmVjeWNsZXI6CiAgICByaW5nOgogICAgICBrdnN0b3JlOgogICAgICAgIHN0b3JlOiBpbm1lbW9yeQogICAgICByZXBsaWNhdGlvbl9mYWN0b3I6IDEKbGltaXRzX2NvbmZpZzoKICBlbmZvcmNlX21ldHJpY19uYW1lOiBmYWxzZQpzY2hlbWFfY29uZmlnOgogIGNvbmZpZ3M6CiAgLSBmcm9tOiAyMDE4LTA0LTE1CiAgICBpbmRleDoKICAgICAgcGVyaW9kOiAxNjhoCiAgICAgIHByZWZpeDogaW5kZXhfCiAgICBvYmplY3Rfc3RvcmU6IGZpbGVzeXN0ZW0KICAgIHNjaGVtYTogdjkKICAgIHN0b3JlOiBib2x0ZGIKc2VydmVyOgogIGh0dHBfbGlzdGVuX3BvcnQ6IDMxMDAKc3RvcmFnZV9jb25maWc6CiAgYm9sdGRiOgogICAgZGlyZWN0b3J5OiAvZGF0YS9sb2tpL2luZGV4CiAgZmlsZXN5c3RlbToKICAgIGRpcmVjdG9yeTogL2RhdGEvbG9raS9jaHVua3MKdGFibGVfbWFuYWdlcjoKICByZXRlbnRpb25fZGVsZXRlc19lbmFibGVkOiBmYWxzZQogIHJldGVudGlvbl9wZXJpb2Q6IDAK

- apiVersion: v1
  kind: Service
  metadata:
    name: ${LOKI_SERVICE_NAME}
    labels:
      app: ${LOKI_SERVICE_NAME}
      chart: loki-0.8.4
      release: ${LOKI_SERVICE_NAME}
      heritage: Tiller
    annotations:
      {}   
  spec:
    type: ClusterIP
    ports:
      - port: 3100
        protocol: TCP
        name: http-metrics
        targetPort: http-metrics
    selector:
      app: loki
      release: ${LOKI_SERVICE_NAME}

- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    labels:
      app: ${LOKI_SERVICE_NAME}
    name: ${LOKI_SERVICE_NAME}
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: ${LOKI_SERVICE_NAME}
      deploymentconfig: ${LOKI_SERVICE_NAME}
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          checksum/config: 5102c215461ac13d341f03fe231621a879c933d0bb3576468ea33f5e4e973fe6
          prometheus.io/port: http-metrics
          prometheus.io/scrape: "true"
        labels:
          app: ${LOKI_SERVICE_NAME}
          deploymentconfig: ${LOKI_SERVICE_NAME}
      spec:
        containers:
          - name: loki
            image: "grafana/loki:latest"
            imagePullPolicy: Always
            args:
              - "-config.file=/etc/loki/loki.yaml"            
            volumeMounts:
              - name: config
                mountPath: /etc/loki
              - name: storage
                mountPath: "/data"
                subPath: 
            ports:
              - name: http-metrics
                containerPort: 3100
                protocol: TCP
            livenessProbe:
              httpGet:
                path: /ready
                port: http-metrics
              initialDelaySeconds: 45
            
            readinessProbe:
              httpGet:
                path: /ready
                port: http-metrics
              initialDelaySeconds: 45
            
            resources:
              {}
            
            securityContext:
              readOnlyRootFilesystem: true
            env:
              - name: JAEGER_AGENT_HOST
                value: ""
        nodeSelector:
          {}
        
        affinity:
          {}
        
        tolerations:
          []
        
        terminationGracePeriodSeconds: 30
        volumes:
          - name: config
            secret:
              secretName: ${LOKI_SERVICE_NAME}
          - name: storage
            emptyDir: {}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${LOKI_SERVICE_NAME}
        from:
          kind: ImageStreamTag
          name: ${LOKI_SERVICE_NAME}:latest
          namespace: ${NAMESPACE}
      type: ImageChange
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    generation: 2
    labels:
      app: ${LOKI_SERVICE_NAME}
    name: ${LOKI_SERVICE_NAME}
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: grafana/loki:latest
      from:
        kind: DockerImage
        name: grafana/loki:latest
      generation: 2
      importPolicy: {}
      name: latest
      referencePolicy:
        type: Source
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    annotations:
      openshift.io/host.generated: "true"
    labels:
      app: ${LOKI_SERVICE_NAME}
    name: ${LOKI_SERVICE_NAME}
  spec:
    host: ${LOKI_SERVICE_NAME}-${NAMESPACE}.${ROUTE_SUBDOMAIN}
    port:
      targetPort: http-metrics
    to:
      kind: Service
      name: ${LOKI_SERVICE_NAME}
      weight: 100
    wildcardPolicy: None

parameters:
- description: Maximum amount of memory the container can use.
  displayName: Memory Limit
  name: MEMORY_LIMIT
  required: true
  value: 512Mi
- description: The namespace this templated is deployed into.
  displayName: Namespace
  name: NAMESPACE
  value: wp9gel-tools
- description: The name of the Loki service to connect to.
  displayName: Loki Service Name
  name: LOKI_SERVICE_NAME
  required: true
  value: loki
- description: Default route subdomain
  displayName: Route subdomain
  name: ROUTE_SUBDOMAIN
  required: true
  value: pathfinder.gov.bc.ca