#!/usr/bin/env groovy

//ENV Vars
def TOOLS_NAMESPACE = "s4g19x-poornima-sivanand-openshift201-may2019-tools"
def DEV_NAMESPACE = "s4g19x-poornima-sivanand-openshift201-may2019-dev"
def PROD_NAMESPACE = "s4g19x-poornima-sivanand-openshift201-may2019-prod"


//Pipeline
node {
            stage ('Build in Tools Namespace'){
                dir ('simple_pipeline') {
                    checkout scm
                    timeout (time: 600, unit: 'SECONDS'){
                        openshift.withCluster() {
                        openshift.withProject("${TOOLS_NAMESPACE}") {
                                def blackboxSelector = openshift.selector("bc", "blackboxexporter")
                                try {
                                    blackboxSelector.object()
                                    builds = blackboxSelector.related( "builds" )
                                } catch (Throwable t) {
                                    nb = openshift.newBuild( "https://github.com/poornima-sivanand/devops-platform-workshops-labs.git#poornima-sivanand-201", "--context-dir=blackbox_exporter", "--name=blackboxexporter" )

                                    // Print out information about the objects created by newBuild
                                    echo "newBuild created: ${nb.count()} objects : ${nb.names()}"

                                    // Filter non-BuildConfig objects and create selector which will find builds related to the BuildConfig
                                    builds = nb.narrow("bc").related( "builds" )
                                }
                                    openshift.selector("bc", "blackboxexporter").startBuild("--wait")
                                    builds.watch {
                                    // 'it' is bound to the builds selector.
                                    // Continue to watch until at least one build is detected
                                    if ( it.count() == 0 ) {
                                        return false
                                    }
                                    // Print out the build's name and terminate the watch
                                    echo "Detected new builds created by buildconfig: ${it.names()}"
                                    return true
                                    }

                                    echo "Waiting for builds to complete..."

                                    // Like a watch, but only terminate when at least one selected object meets condition
                                    builds.untilEach {
                                        return it.object().status.phase == "Complete"
                                    }
                        }
                        }
                    }

             }
        }
        stage('Promote to DEV') {
                openshift.withCluster() {
                    openshift.tag("blackboxexporter:latest", "blackboxexporter:dev")
                }
            }
        stage('Create DEV') {
            openshift.withCluster() {
                openshift.withProject("${DEV_NAMESPACE}") {
                                def blackboxdcSelector = openshift.selector("dc", "blackboxexporter")
                                try {
                                    blackboxdcSelector.object()
                                    deploymentconfig = blackboxdcSelector.related( "deploymentconfig" )
                                } catch (Throwable t) {
                                    na = openshift.newApp("${TOOLS_NAMESPACE}/blackboxexporter:dev", "--name=blackboxexporter").narrow('svc').expose()

                                    // Print out information about the objects created by newBuild
                                    echo "newApp created: ${na.count()} objects : ${na.names()}"

                                }
                }
            }
            }  

        stage('Promote to PROD') {
                openshift.withCluster() {
                    openshift.tag("blackboxexporter:latest", "blackboxexporter:prod")
                }
            }
        stage('Create PROD') {
            openshift.withCluster() {
                openshift.withProject("${PROD_NAMESPACE}") {
                                def blackboxdcSelector = openshift.selector("dc", "blackboxexporter")
                                try {
                                    blackboxdcSelector.object()
                                    deploymentconfig = blackboxdcSelector.related( "deploymentconfig" )
                                } catch (Throwable t) {
                                    na = openshift.newApp("${TOOLS_NAMESPACE}/blackboxexporter:prod", "--name=blackboxexporter").narrow('svc').expose()

                                    // Print out information about the objects created by newBuild
                                    echo "newApp created: ${na.count()} objects : ${na.names()}"

                                }
                }
            }
            }  

}